// <auto-generated />
using System;
using FoodTruckApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodTruckApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250729182154_AddKennitala")]
    partial class AddKennitala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodTruckApp.Code.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("FoodTruckApp.Data.NewOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("NewOrders");
                });

            modelBuilder.Entity("FoodTruckApp.Models.AlergenesTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlergenDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AlergenNum")
                        .HasColumnType("integer");

                    b.Property<string>("AlergenPicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlergenesTypes");
                });

            modelBuilder.Entity("FoodTruckApp.Models.ItemOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NewOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("NumOfDishes")
                        .HasColumnType("integer");

                    b.Property<double>("PricePerOne")
                        .HasColumnType("double precision");

                    b.Property<int>("RestaurantItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewOrderId");

                    b.HasIndex("RestaurantItemId");

                    b.ToTable("ItemsOfOrders");
                });

            modelBuilder.Entity("FoodTruckApp.Models.Kennitala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KennitalaName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KennitalaNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NewOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewOrderId");

                    b.ToTable("Kennitalas");
                });

            modelBuilder.Entity("FoodTruckApp.Models.OpenHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Closehour")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Openhour")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("OpenHours");
                });

            modelBuilder.Entity("FoodTruckApp.Models.OpenStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OpenStatus");
                });

            modelBuilder.Entity("FoodTruckApp.Models.RestItemAlergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlergenesTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlergenesTypesId");

                    b.HasIndex("RestaurantItemId");

                    b.ToTable("restItemAlergens");
                });

            modelBuilder.Entity("FoodTruckApp.Models.RestaurantItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ability")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RestaurantItems");
                });

            modelBuilder.Entity("FoodTruckApp.Models.ItemOrder", b =>
                {
                    b.HasOne("FoodTruckApp.Data.NewOrder", "NewOrder")
                        .WithMany("Items")
                        .HasForeignKey("NewOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodTruckApp.Models.RestaurantItem", "RestaurantItem")
                        .WithMany()
                        .HasForeignKey("RestaurantItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewOrder");

                    b.Navigation("RestaurantItem");
                });

            modelBuilder.Entity("FoodTruckApp.Models.Kennitala", b =>
                {
                    b.HasOne("FoodTruckApp.Data.NewOrder", "NewOrder")
                        .WithMany()
                        .HasForeignKey("NewOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewOrder");
                });

            modelBuilder.Entity("FoodTruckApp.Models.RestItemAlergen", b =>
                {
                    b.HasOne("FoodTruckApp.Models.AlergenesTypes", "AlergenesTypes")
                        .WithMany()
                        .HasForeignKey("AlergenesTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodTruckApp.Models.RestaurantItem", "RestaurantItem")
                        .WithMany("Alergenes")
                        .HasForeignKey("RestaurantItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlergenesTypes");

                    b.Navigation("RestaurantItem");
                });

            modelBuilder.Entity("FoodTruckApp.Data.NewOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodTruckApp.Models.RestaurantItem", b =>
                {
                    b.Navigation("Alergenes");
                });
#pragma warning restore 612, 618
        }
    }
}
